// brain.ts — write scout artifacts into GBrain via its CLI.
// Phase 0/1: shell-out to `gbrain put`. Phase 5+: native LeScout brain.

import { spawn } from "node:child_process";
import type { ScoutRepoExtraction } from "./extract.ts";
import { summarizeTree } from "./extract.ts";
import { parseRepoIdentity, sanitizeLabel } from "./security.ts";

// Resolve to the user's gbrain binary via $PATH by default; override with GBRAIN_BIN.
const GBRAIN_BIN = process.env.GBRAIN_BIN ?? "gbrain";

/** Slug shape we use for scouted repos/docs. */
export function repoSlug(url: URL, kind: "repo" | "docs" = "repo"): string {
  const { owner, name, host } = parseRepoIdentity(url);
  // host kept short to fit alongside owner/name
  const shortHost = host.replace(/\.com$|\.org$/, "");
  const prefix = kind === "docs" ? "docs" : "repos";
  return `${prefix}/${shortHost}/${owner}/${name}`;
}

/** Render a scout result as a markdown brain page. */
export function renderRepoPage(extraction: ScoutRepoExtraction, kind: "repo" | "docs" = "repo"): string {
  const url = new URL(extraction.url);
  const { owner, name } = parseRepoIdentity(url);
  const slug = repoSlug(url, kind);

  const frontmatter = [
    "---",
    `title: ${owner}/${name}${kind === "docs" ? " (docs)" : ""}`,
    `type: ${kind}`,
    `source_url: ${extraction.url}`,
    `host: ${url.hostname}`,
    `owner: ${owner}`,
    `name: ${name}`,
    `sha: ${extraction.sha}`,
    `scouted_at: ${extraction.scoutedAt}`,
    `file_count: ${extraction.fileCount}`,
    `dir_count: ${extraction.dirCount}`,
    `size_bytes: ${extraction.sizeBytes}`,
    `tags: [scouted, ${kind}]`,
    "---",
    "",
  ].join("\n");

  const sections: string[] = [];
  sections.push(`# ${owner}/${name}`);
  sections.push("");
  sections.push(`> Scouted from ${extraction.url}`);
  sections.push(`> SHA \`${extraction.sha.slice(0, 12)}\` · ${extraction.fileCount} files · ${(extraction.sizeBytes / 1024).toFixed(1)} KB`);
  sections.push("");

  if (extraction.lastCommit) {
    const c = extraction.lastCommit;
    sections.push(`**Last commit:** ${c.isoDate} — ${sanitizeLabel(c.author, 80)} — ${sanitizeLabel(c.subject, 160)}`);
    sections.push("");
  }

  // Filetree summary.
  sections.push("## Filetree");
  sections.push("");
  sections.push("```");
  sections.push(summarizeTree(extraction.tree, 80));
  sections.push("```");
  sections.push("");

  // Manifests — show first ~80 lines of each.
  if (Object.keys(extraction.manifests).length > 0) {
    sections.push("## Manifests");
    sections.push("");
    for (const [fname, body] of Object.entries(extraction.manifests)) {
      sections.push(`### \`${fname}\``);
      sections.push("");
      sections.push("```" + langFor(fname));
      sections.push(body.split("\n").slice(0, 80).join("\n"));
      sections.push("```");
      sections.push("");
    }
  }

  // READMEs / agent files.
  if (Object.keys(extraction.docs).length > 0) {
    sections.push("## Documentation");
    sections.push("");
    for (const [fname, body] of Object.entries(extraction.docs)) {
      sections.push(`### \`${fname}\``);
      sections.push("");
      // Cap docs to first 300 lines to keep brain pages tractable.
      sections.push(body.split("\n").slice(0, 300).join("\n"));
      sections.push("");
    }
  }

  // TODOs.
  if (extraction.todos.length > 0) {
    sections.push("## TODOs / FIXMEs");
    sections.push("");
    for (const t of extraction.todos.slice(0, 30)) {
      sections.push(`- \`${t.path}:${t.line}\` — ${sanitizeLabel(t.text, 200)}`);
    }
    sections.push("");
  }

  sections.push(`---`);
  sections.push(`*Auto-generated by \`lescout repo\` — slug: \`${slug}\`*`);

  return frontmatter + sections.join("\n");
}

function langFor(filename: string): string {
  if (filename.endsWith(".json")) return "json";
  if (filename.endsWith(".toml")) return "toml";
  if (filename.endsWith(".yaml") || filename.endsWith(".yml")) return "yaml";
  if (filename === "go.mod") return "go-mod";
  if (filename === "requirements.txt") return "text";
  return "";
}

/** Write the rendered page into GBrain. Resolves to the slug on success. */
export async function writeToBrain(slug: string, markdown: string): Promise<{ slug: string; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(GBRAIN_BIN, ["put", slug], { stdio: ["pipe", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.stderr.on("data", (d) => (stderr += d.toString()));
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve({ slug, stdout, stderr });
      else reject(new Error(`gbrain put exited ${code}\n${stderr}`));
    });
    child.stdin.write(markdown);
    child.stdin.end();
  });
}
