// context.ts — caveman-compress: gather everything in the brain about a target
// into ONE dense markdown file under a token budget. The killer primitive for
// "agent loads compact project context, then builds".

import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";

const GBRAIN_BIN = process.env.GBRAIN_BIN ?? "/Users/aryateja/.bun/bin/gbrain";

export interface ContextOptions {
  /** Approx token budget for the output. Default 30000. */
  tokenBudget?: number;
  /** Number of brain pages to fetch per source. Default 12. */
  pagesPerSource?: number;
  /** Also write the compacted bundle back to the brain as a page. Default true. */
  writeToBrain?: boolean;
}

export interface ContextReport {
  target: string;
  outPath: string;
  brainSlug?: string;
  pagesIncluded: number;
  estTokens: number;
  estChars: number;
}

interface BrainHit {
  slug: string;
  title: string;
  type: string;
  score: number;
  chunkText: string;
}

export async function buildContext(target: string, opts: ContextOptions = {}): Promise<ContextReport> {
  const tokenBudget = opts.tokenBudget ?? 30000;
  const pagesPerSource = opts.pagesPerSource ?? 12;
  const charBudget = tokenBudget * 4; // rough 4 chars / token approximation

  // 1. Hybrid query — best matches across the whole brain.
  const queryHits = await brainQuery(target, pagesPerSource * 2);

  // 2. Slug-prefix sweeps for each source type, filtered by name match.
  const repoHits = await brainListByPrefix("repos/", pagesPerSource, target);
  const docsHits = await brainListByPrefix("docs/", pagesPerSource, target);
  const sessionHits = await brainListByPrefix("sessions/", pagesPerSource, target);
  const noteHits = await brainListByPrefix("docs/", pagesPerSource, target); // gbrain notes share docs/ tree
  // (split shown for clarity; gbrain's `list` already covers prefixes broadly)

  // Combine + dedupe by slug; query hits already have chunkText, list hits need fetching.
  const bySlug = new Map<string, BrainHit>();
  for (const h of [...queryHits, ...repoHits, ...docsHits, ...sessionHits, ...noteHits]) {
    const existing = bySlug.get(h.slug);
    if (!existing) bySlug.set(h.slug, h);
    else if (!existing.chunkText && h.chunkText) bySlug.set(h.slug, h); // prefer the one with content
  }
  const allHits = [...bySlug.values()];

  // Enrich any hit whose chunkText is too thin (< 500 chars) by fetching
  // the full page. Cap fetches to avoid runaway latency on huge bundles.
  const FETCH_CAP = 30;
  let fetched = 0;
  for (const h of allHits) {
    if (fetched >= FETCH_CAP) break;
    if (h.chunkText && h.chunkText.length >= 500) continue;
    try {
      const page = await brainGet(h.slug);
      if (page) {
        const body = stripFrontmatter(page);
        // Keep more for high-scoring hits; trim aggressively for low-score ones.
        const cap = h.score >= 0.5 ? 5000 : 2500;
        h.chunkText = body.slice(0, cap);
        fetched++;
      }
    } catch {
      /* skip */
    }
  }

  // 3. Compress: keep highest-signal chunks first, drop dupes, respect budget.
  allHits.sort((a, b) => (b.score || 0) - (a.score || 0));
  const buckets: Record<string, BrainHit[]> = {
    docs: [],
    repos: [],
    sessions: [],
    notes: [],
    concepts: [],
    other: [],
  };
  for (const h of allHits) {
    const bucket = bucketFor(h.slug, h.type);
    buckets[bucket]!.push(h);
  }

  // 4. Render the bundle, stopping when the char budget is exhausted.
  const head = [
    "---",
    `title: Context bundle: ${target}`,
    `type: context-bundle`,
    `target: ${target}`,
    `assembled_at: ${new Date().toISOString()}`,
    `token_budget: ${tokenBudget}`,
    `tags: [context, lescout, caveman-compress]`,
    "---",
    "",
    `# Context — ${target}`,
    "",
    `> Compact context bundle for fresh agents. Load this file in your initial`,
    `> turn instead of re-deriving context. Generated by \`lescout context\`.`,
    "",
    "## How to use",
    "",
    `1. New chat: \`Read ${pathHint(target)} before answering anything.\``,
    `2. Or: paste this file's body directly as the first user message.`,
    `3. The bundle is hybrid-search-ranked from your GBrain — newer ingests update via \`lescout context ${target}\` again.`,
    "",
    "## Table of contents",
    "",
  ];

  const sections: string[] = [];
  const tocLines: string[] = [];
  let usedChars = head.join("\n").length;
  let pagesIncluded = 0;

  const ORDER: Array<keyof typeof buckets> = ["docs", "repos", "sessions", "notes", "concepts", "other"];
  for (const bucketName of ORDER) {
    const items = buckets[bucketName]!;
    if (items.length === 0) continue;

    const sectionHeader = `### ${capitalize(bucketName)} (${items.length})`;
    tocLines.push(`- ${sectionHeader.replace(/^###\s+/, "")}`);

    const sectionBody: string[] = ["", sectionHeader, ""];
    for (const h of items) {
      // Per-item budget: roughly evenly distributed; cap per item at 4000 chars.
      const remaining = charBudget - usedChars;
      if (remaining < 1000) break;
      const itemBudget = Math.min(remaining, 4000);

      const item = renderItem(h, itemBudget);
      if (usedChars + item.length > charBudget) break;

      sectionBody.push(item);
      usedChars += item.length;
      pagesIncluded++;
    }
    sections.push(sectionBody.join("\n"));
    if (usedChars >= charBudget) break;
  }

  const body = [...head, ...tocLines, "", ...sections, "", "---", `*Assembled ${pagesIncluded} chunks · ~${Math.round(usedChars / 4)} tokens of ${tokenBudget} budget.*`].join("\n");

  // 5. Write to disk.
  const outDir = join(homedir(), ".lescout", "context");
  await mkdir(outDir, { recursive: true });
  const date = new Date().toISOString().slice(0, 10);
  const safeTarget = target.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "").slice(0, 60);
  const outPath = join(outDir, `${safeTarget}-${date}.md`);
  await Bun.write(outPath, body);

  // 6. Optionally write to the brain itself.
  let brainSlug: string | undefined;
  if (opts.writeToBrain !== false) {
    brainSlug = `context/${safeTarget}/${date}`;
    try {
      await brainPut(brainSlug, body);
    } catch {
      brainSlug = undefined;
    }
  }

  return {
    target,
    outPath,
    brainSlug,
    pagesIncluded,
    estTokens: Math.round(usedChars / 4),
    estChars: usedChars,
  };
}

function bucketFor(slug: string, type: string): string {
  if (slug.startsWith("docs/")) return "docs";
  if (slug.startsWith("repos/")) return "repos";
  if (slug.startsWith("sessions/")) return "sessions";
  if (type === "concept") return "concepts";
  if (type === "note") return "notes";
  return "other";
}

function renderItem(h: BrainHit, budgetChars: number): string {
  const title = h.title || h.slug;
  const trimmed = (h.chunkText || "").slice(0, Math.max(0, budgetChars - 200)).trim();
  return [
    `**${title}**  \`${h.slug}\`  · score ${(h.score ?? 0).toFixed(2)}`,
    "",
    trimmed,
    "",
  ].join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function pathHint(target: string): string {
  return `~/.lescout/context/${target.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-<date>.md`;
}

// ──────────────────────────── gbrain shell-outs ────────────────────────────

function runGbrain(args: string[]): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn(GBRAIN_BIN, args, { stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.stderr.on("data", (d) => (stderr += d.toString()));
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve(stdout);
      else reject(new Error(`gbrain ${args.join(" ")} exited ${code}\n${stderr}`));
    });
  });
}

async function brainQuery(q: string, limit: number): Promise<BrainHit[]> {
  try {
    const out = await runGbrain(["query", q, "--limit", String(limit), "--json"]);
    const parsed = JSON.parse(out);
    if (Array.isArray(parsed)) {
      return parsed.map((r) => ({
        slug: String(r.slug ?? ""),
        title: String(r.title ?? ""),
        type: String(r.type ?? ""),
        score: Number(r.score ?? 0),
        chunkText: String(r.chunk_text ?? r.content ?? ""),
      }));
    }
  } catch {
    // gbrain query may not support --json. Fallback: parse plain text.
  }
  try {
    const out = await runGbrain(["query", q, "--limit", String(limit)]);
    return parsePlainQuery(out);
  } catch {
    return [];
  }
}

function parsePlainQuery(s: string): BrainHit[] {
  const hits: BrainHit[] = [];
  // Plain output lines look like: "[0.5827] slug -- chunk text"
  const re = /\[(\d+\.\d+)\]\s+([^\s]+)\s+--\s+(.+)/;
  for (const line of s.split("\n")) {
    const m = line.match(re);
    if (m) hits.push({ slug: m[2]!, title: "", type: "", score: Number(m[1]), chunkText: m[3]! });
  }
  return hits;
}

async function brainListByPrefix(prefix: string, limit: number, grep: string): Promise<BrainHit[]> {
  try {
    const out = await runGbrain(["list", "--slug-prefix", prefix, "-n", String(limit * 4)]);
    const hits: BrainHit[] = [];
    const grepLower = grep.toLowerCase();
    for (const line of out.split("\n")) {
      const parts = line.split("\t");
      if (parts.length < 4) continue;
      const slug = parts[0]!;
      const type = parts[1] ?? "";
      const title = parts[3] ?? "";
      if (!slug.startsWith(prefix)) continue;
      const matchScore = matchScoreFor(slug, title, grepLower);
      if (matchScore > 0) {
        hits.push({ slug, title, type, score: matchScore, chunkText: "" });
      }
    }
    hits.sort((a, b) => b.score - a.score);
    return hits.slice(0, limit);
  } catch {
    return [];
  }
}

function matchScoreFor(slug: string, title: string, target: string): number {
  const s = slug.toLowerCase();
  const t = title.toLowerCase();
  if (s.includes(target)) return 2;
  if (t.includes(target)) return 1.5;
  // partial: any word of target appears
  const words = target.split(/[\s-_]+/).filter((w) => w.length > 2);
  let score = 0;
  for (const w of words) if (s.includes(w) || t.includes(w)) score += 0.5;
  return score;
}

async function brainGet(slug: string): Promise<string | null> {
  try {
    return await runGbrain(["get", slug]);
  } catch {
    return null;
  }
}

function stripFrontmatter(s: string): string {
  if (!s.startsWith("---")) return s;
  const closeIdx = s.indexOf("\n---", 4);
  if (closeIdx === -1) return s;
  return s.slice(closeIdx + 4).trimStart();
}

async function brainPut(slug: string, markdown: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(GBRAIN_BIN, ["put", slug], { stdio: ["pipe", "pipe", "pipe"] });
    let stderr = "";
    child.stderr.on("data", (d) => (stderr += d.toString()));
    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`gbrain put ${slug} exited ${code}\n${stderr}`));
    });
    child.stdin.write(markdown);
    child.stdin.end();
  });
}
